
services:
  ui:
    image: taleemhelp/ui:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
  # keep the :latest images and keep latest updated
  api: 
    image: taleemhelp/api:latest 
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LOCAL_MONGO_URI=mongodb://admin:password@local_mongo:27017/localDb?authSource=admin
    depends_on:
      - local_mongo

  local_mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
